//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationIdentity.Web.Views.Account {
    
    
    public partial class Manage {
        
        /// <summary>
        /// AssignedOAuthProviders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NavigationIdentity.Web.Views.Account.Controls.AssignedOAuthProviders AssignedOAuthProviders;
        
        /// <summary>
        /// UnassignedOAuthProviders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NavigationIdentity.Web.Views.Account.Controls.UnassignedOAuthProviders UnassignedOAuthProviders;
    }
}
